# Generated by Django 5.1.2 on 2024-11-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-deposit_date'], 'verbose_name': 'Saving'},
        ),
        migrations.AlterModelOptions(
            name='savingaccount',
            options={'verbose_name': 'Savings Account'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
