# Generated by Django 5.1.2 on 2024-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_savingaccount_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
