# Generated by Django 5.1.2 on 2024-11-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savingaccount_current_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='current_amount',
        ),
    ]
