# Generated by Django 5.1.2 on 2024-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_savingaccount_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='deposit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
